[package]
name = "mysocket"
version = "0.1.0"
authors = ["Hamid Ghadyani <hamid@hamid.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "*", features = ["unix"] }
